# Generated by Django 4.1.5 on 2023-02-09 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 2, 9, 11, 30, 51, 977920))),
            ],
        ),
    ]
