# Generated by Django 4.1.5 on 2023-02-09 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_catego_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catego',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 11, 33, 40, 432734)),
        ),
    ]
