# Generated by Django 4.1.5 on 2023-02-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='porta/img/')),
                ('url', models.URLField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.catego')),
            ],
        ),
    ]
