# Generated by Django 4.1.5 on 2023-02-09 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lector', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 2, 9, 11, 30, 51, 977920))),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.projecto')),
            ],
        ),
    ]
